version: '3.1'
services:   
   frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    container_name: front
    ports:
      - "81:81"
    depends_on:
      - db 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: back
    ports:
      - "80:80"
    depends_on:
      - db